### PR TITLE
Rename ContentProjectionNormalizer to ContentNormalizer

### PR DESCRIPTION
**Pull request by alexander-schranz**
The normalizer should not depend on the ContentProjectionInterface, it should work with every contentable object.

### CODE REVIEW

**Comment by alexander-schranz** [comment]
Did see #107 just know. You want to include `Data` in the service name?

**Comment by nnatter** [comment]
i think i would either include `Data` here or remove it from the `DataMapper` classes. what do you think?

**Comment by alexander-schranz** [comment]
@nnatter thinking about it I'm not sure if its the same as `ContentNormalizer` does not normalize data it does normalize a object and the output is data, so I personally would more go with this way or removing it also from Mapper namespaces.

**Comment by nnatter** [comment]
yes, you are right 🙂 sounds good

**Pull request merged**
