### PR TITLE
Declare entity-independent methods on marker interfaces as static

### PR DESCRIPTION
**Pull request by nnatter**
- [ ] `RoutableInterface:: getContentClass`
- [x] `TemplateInterface:: getTemplateType`
- [ ] `WorkflowInterface:: getWorkflowName`

### CODE REVIEW

**Comment by alexander-schranz** [comment]
Making it static will break exist projects code. Should we create a tag maybe before and then provide a UPGRADE path?

**Comment by alexander-schranz** [comment]
The tests are failing because prophecy can not mock static methods.

**Comment by nnatter** [comment]
mocking of static methods is really a pain 🤔 need to think about this..

**Comment by nnatter** [comment]
Replaced by #117

**Pull request closed without merging**
